/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.virtuatech.gestao_de_treinamentos.visao.formulario;

import com.virtuatech.gestao_de_treinamentos.visao.modelo.CartaoModelo;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Renato
 */
public class FormularioPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        inicializarCartao();
        jScrollPane1.getViewport().setBackground(Color.WHITE);
    }
    
    private void inicializarCartao(){
        CartaoModelo cartaoModelo = new CartaoModelo(new ImageIcon(getCaminho() + "produto.png"), "Treinamento", "Total 5");
        CartaoModelo cartaoModelo1 = new CartaoModelo(new ImageIcon(getCaminho() + "venda.png"), "Histórico", "Total 2");
        CartaoModelo cartaoModelo2 = new CartaoModelo(new ImageIcon(getCaminho() + "stock.png"), "Colaboradores", "Total 25");
        
        cartao4.setData(cartaoModelo);
        cartao5.setData(cartaoModelo1);
        cartao6.setData(cartaoModelo2);
    }
    
    private String getCaminho(){
        return System.getProperty("user.dir") + "\\src\\main\\java\\com\\virtuatech\\gestao_de_treinamentos\\visao\\icon\\";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cartao5 = new com.virtuatech.gestao_de_treinamentos.visao.componentes.Cartao();
        cartao4 = new com.virtuatech.gestao_de_treinamentos.visao.componentes.Cartao();
        cartao6 = new com.virtuatech.gestao_de_treinamentos.visao.componentes.Cartao();
        panelBoard1 = new com.virtuatech.gestao_de_treinamentos.visao.componentes.PanelBoard();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new com.virtuatech.gestao_de_treinamentos.visao.componentes.Tabela();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        cartao5.setCor1(new java.awt.Color(51, 0, 153));
        cartao5.setCor2(new java.awt.Color(0, 5, 147));
        jPanel1.add(cartao5);

        cartao4.setCor1(new java.awt.Color(69, 30, 161));
        cartao4.setCor2(new java.awt.Color(51, 0, 102));
        jPanel1.add(cartao4);

        cartao6.setCor1(new java.awt.Color(69, 0, 164));
        cartao6.setCor2(new java.awt.Color(0, 0, 102));
        jPanel1.add(cartao6);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 130, 130));
        jLabel1.setText("Histórico de treinamentos");

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Treinamento", "Data", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela1);

        javax.swing.GroupLayout panelBoard1Layout = new javax.swing.GroupLayout(panelBoard1);
        panelBoard1.setLayout(panelBoard1Layout);
        panelBoard1Layout.setHorizontalGroup(
            panelBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBoard1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        panelBoard1Layout.setVerticalGroup(
            panelBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoard1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.virtuatech.gestao_de_treinamentos.visao.componentes.Cartao cartao4;
    private com.virtuatech.gestao_de_treinamentos.visao.componentes.Cartao cartao5;
    private com.virtuatech.gestao_de_treinamentos.visao.componentes.Cartao cartao6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.virtuatech.gestao_de_treinamentos.visao.componentes.PanelBoard panelBoard1;
    private com.virtuatech.gestao_de_treinamentos.visao.componentes.Tabela tabela1;
    // End of variables declaration//GEN-END:variables
}
